from __future__ import annotations
from typing import Protocol, Iterable, Optional
from app.domain.task import Task


class TaskRepository(Protocol):
    def list(self) -> Iterable[Task]: ...
    def get(self, task_id: str) -> Optional[Task]: ...
    def add(self, task: Task) -> Task: ...
    def update(self, task: Task) -> Task: ...
    def delete(self, task_id: str) -> None: ...
